title: Cala's Blog
author: fluiz71
email: fluiz71@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog related to Java programming and Node.js development of sites and apps.  Write an awesome description for your new site here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  fluiz71 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
